export const appConstant = {
    BIOMETRIC_LOGIN: "Biometric Login",
    BIOMETRIC_LOGIN_MESSAGE: "Please login with email and password first.",
    BIOMETRIC_UNAVAILABLE: "Biometric unavailable",
    BIOMETRIC_UNAVAILABLE_MESSAGE: "No biometric authentication is configured on this device.",
    LOGIN_BIOMETRICS: "Login with Biometrics",
    CANCEL: "Cancel",
    PASSWORD_MISMATCH: "Password Mismatch",
    PASSWORD_MISMATCH_MESSAGE: "The password you entered does not match.",
    USERNAME_TAKEN: "Username Taken",
    USERNAME_TAKEN_MESSAGE: "This username is already taken. Please choose another.",
    AUTHENTICATION_FAILED: "Authentication failed",
    UNABLE_TO_LOGIN: "Unable to login",
    WELCOME_BACK: "Welcome back",
    SIGN_IN_TO_CONTINUE_LEARNING: "Sign in to continue learning",
    EMAIL: "Email",
    PASSWORD: "Password",
    EMIL_PLACEHOLDER: "you@example.com",
    FORGOT_PASSWORD: "Forgot password?",
    SIGN_IN: "Sign In",
    DON_T_HAVE_AN_ACCOUNT: "Don't have an account?",
    SIGN_UP: "Sign Up",
    MISSING_FIELDS: "Missing fields",
    PLEASE_FILL_IN_ALL_FIELDS: "Please fill in all fields",
    ACCOUNT_CREATED_SUCCESS: "Account created! Please sign in.",
    OK: "OK",
    ACCOUNT_CREATED_FAILED: "Registration failed",
    STARTING_YOUR_JOURNEY: "Start your learning journey today",
    USERNAME: "Username",
    ALREADY_HAVE_AN_ACCOUNT: "Already have an account? ",
    LOADING_COURSES: "Loading courses...",
    COULDN_T_LOAD_COURSES: "Couldn't load courses",
    COULDN_T_LOAD_COURSES_MESSAGE: "Check your connection and try again",
    RETRY_FETCHING: "Retry Fetching",
    COURSES: "Courses",
    SEARCH_COURSES: "Search courses, instructors...",
    NO_COURSES_FOUND: "No courses found",
    LOADING_MORE: "Loading more...",
    PERMISSION_NEEDED: "Permission needed",
    PLEASE_ALLOW_ACCESS_TO_YOUR_PHOTOS: "Please allow access to your photos",
    UPLOAD_FAILED: "Upload failed",
    COULD_N_T_UPDATE_AVATAR: "Could not update avatar",
    LOG_OUT: "Log out",
    ARE_YOU_SURE_YOU_WANT_TO_LOG_OUT: "Are you sure you want to log out?",
    PROFILE: "Profile",
    COMPLETED: "Completed",
    IN_PROGRESS: "In Progress",
    BOOKMARKED: "Bookmarked",
    OVERALL_PROGRESS: "Overall Progress",
    ACCOUNT: "Account",
    EDIT_PROFILE: "Edit Profile",
    DARK_MODE: "Dark Mode",
    PREFERENCES: "Preferences",
    CONGRATULATIONS: "Congratulations",
    COURSE_MARKED_AS_COMPLETED: "Course marked as completed. You've achieved an amazing milestone!",
    AWESOME: "Awesome",
    FAILED_TO_PARSE_WEBVIEW_MESSAGE: "Failed to parse webview message",
    COURSE_PLAYER: "Course Player",
    DEBUG_HEADERS: "Debug Headers",
    UNKNOWN_LOAD_ERROR: "Unknown load error",
    CONNECTION_ERROR: "Connection error",
    COURSE_NOT_FOUND: "Course Not Found",
    THIS_COURSE_IS_NO_LONGER_AVAILABLE: "This course is no longer available",
    THE_COURSE_YOU_ARE_LOOKING_FOR_MIGHT_HAVE_BEEN_REMOVED_OR_IS_UNAVAILABLE: "The course you are looking for might have been removed or is unavailable.",
    GO_BACK: "Go Back",
    ENROLLED_SUCCESSFULLY: "Enrolled Successfully!",
    ENROLLED_SUCCESSFULLY_MESSAGE: "Congratulations! You are now enrolled in this course. Start learning today!",
    START_LEARNING: "Start Learning",
    DISMISS: "Dismiss",
    INSTRUCTOR: "Instructor",
    COURSE_FEE: "Course Fee",
    LIFETIME_ACCESS: "Lifetime Access",
    ABOUT_THIS_COURSE: "About this course",
    HOURS_HIGH_QUALITY_VIDEO: "12 hours high-quality on-demand video",
    ARTICLES_AND_DOWNLOADABLE_RESOURCES: "4 articles and downloadable resources",
    CERTIFICATE_OF_COMPLETION_UPON_REQUEST: "Certificate of completion upon request",
    ENROLLING_DOTS: "Enrolling...",
    ENROLL: "Enroll",
    RESUME_LEARNING: "Resume Learning",
    ENROLL_NOW: "Enroll Now",
    PLEASE_ENTER_BOTH_EMAIL_AND_PASSWORD: "Please enter both email and password",
    LOGIN_FAILED: "Login failed",
    SOMETHING_WENT_WRONG: "Something went wrong",
}


